/**
 * Pure generators (no fs) — unit-tested, used by build.ts.
 */
import {
  ACCENTS,
  ACCENT_HUE_VAR,
  BRAND,
  BREAKPOINTS,
  CONTENT_WIDTHS,
  DATA_ATTRS,
  DEFAULT_PREFS,
  DENSITY_VARS,
  FONTS,
  LEGACY_KEYS,
  MOTION_VARS,
  PREFS_STORAGE_KEY,
  RADIUS_VARS,
  ROLES,
  SURFACE_VARS,
  TV,
  Z_INDEX,
  oklchCss,
} from "./tokens.ts";

const HEADER = `/* GENERATED by packages/design-tokens — do not edit. Run: pnpm -C packages/design-tokens build */`;

function block(selector: string, vars: Record<string, string>, indent = "  "): string {
  const lines = Object.entries(vars).map(([k, v]) => `${indent}${k}: ${v};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

function roleVars(mode: "light" | "dark"): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, c] of Object.entries(ROLES[mode])) out[`--${name}`] = oklchCss(c);
  // exposed L/C of primary so glow/gradients can re-use them with the live hue
  out["--primary-l"] = String(ROLES[mode].primary.l);
  out["--primary-c"] = String(ROLES[mode].primary.c);
  const dark = mode === "dark";
  out["--brand"] = dark ? BRAND.violetDark : BRAND.violet;
  out["--brand-2"] = dark ? BRAND.magentaDark : BRAND.magenta;
  out["--brand-accent"] = dark ? BRAND.cyanDark : BRAND.cyan;
  out["--brand-gradient"] = dark ? BRAND.gradientDark : BRAND.gradient;
  out["--accent-gradient"] =
    `linear-gradient(135deg, oklch(var(--primary-l) var(--primary-c) var(--accent-h)) 0%, oklch(var(--primary-l) var(--primary-c) calc(var(--accent-h) + 45)) 100%)`;
  return out;
}

/** Shared body of both CSS flavours: root defaults + every dimension selector. */
export function dimensionCss(): string {
  const parts: string[] = [];
  const root: Record<string, string> = {
    [ACCENT_HUE_VAR]: String(ACCENTS[DEFAULT_PREFS.accent as keyof typeof ACCENTS].hue),
    "--radius": RADIUS_VARS[DEFAULT_PREFS.radius],
    "--font-sans": FONTS.sans,
    "--font-heading": FONTS.heading,
    "--font-mono": FONTS.mono,
    "--deck-a": BRAND.deckA,
    "--deck-b": BRAND.deckB,
    "--deck-c": BRAND.deckC,
    "--deck-d": BRAND.deckD,
    "--safe-top": "env(safe-area-inset-top, 0px)",
    "--safe-right": "env(safe-area-inset-right, 0px)",
    "--safe-bottom": "env(safe-area-inset-bottom, 0px)",
    "--safe-left": "env(safe-area-inset-left, 0px)",
    ...Object.fromEntries(Object.entries(CONTENT_WIDTHS).map(([k, v]) => [`--content-${k}`, v])),
    ...Object.fromEntries(Object.entries(Z_INDEX).map(([k, v]) => [`--z-${k}`, String(v)])),
    ...SURFACE_VARS[DEFAULT_PREFS.surface],
    ...DENSITY_VARS[DEFAULT_PREFS.density],
    ...MOTION_VARS[DEFAULT_PREFS.motion],
    ...roleVars("light"),
    "color-scheme": "light",
  };
  parts.push(block(":root", root));
  parts.push(block(`:root[${DATA_ATTRS.mode}="dark"], .dark`, { ...roleVars("dark"), "color-scheme": "dark" }));
  for (const [name, def] of Object.entries(ACCENTS))
    parts.push(block(`:root[${DATA_ATTRS.accent}="${name}"]`, { [ACCENT_HUE_VAR]: String(def.hue) }));
  for (const [name, vars] of Object.entries(SURFACE_VARS)) parts.push(block(`:root[${DATA_ATTRS.surface}="${name}"]`, vars));
  for (const [name, vars] of Object.entries(DENSITY_VARS)) parts.push(block(`:root[${DATA_ATTRS.density}="${name}"]`, vars));
  for (const [name, v] of Object.entries(RADIUS_VARS)) parts.push(block(`:root[${DATA_ATTRS.radius}="${name}"]`, { "--radius": v }));
  for (const [name, vars] of Object.entries(MOTION_VARS)) parts.push(block(`:root[${DATA_ATTRS.motion}="${name}"]`, vars));
  parts.push(`@media (prefers-reduced-motion: reduce) {\n${block("  :root", MOTION_VARS.reduced, "    ")}\n}`);
  parts.push(
    block(":root[data-tv]", {
      "font-size": TV.rootFontSize,
      "--overscan-x": TV.overscanX,
      "--overscan-y": TV.overscanY,
      "--focus-ring-w": TV.focusRingWidth,
      "--card-scale-focused": TV.cardScaleFocused,
    }),
  );
  return parts.join("\n\n");
}

/** Tailwind v4 flavour — `@theme inline` maps CSS vars to utilities. Consumers `@import "tailwindcss"` first. */
export function tailwindCss(): string {
  const theme: Record<string, string> = {
    "--font-sans": "var(--font-sans)",
    "--font-heading": "var(--font-heading)",
    "--font-mono": "var(--font-mono)",
    "--color-brand": "var(--brand)",
    "--color-brand-2": "var(--brand-2)",
    "--color-brand-accent": "var(--brand-accent)",
    "--color-deck-a": "var(--deck-a)",
    "--color-deck-b": "var(--deck-b)",
    "--color-deck-c": "var(--deck-c)",
    "--color-deck-d": "var(--deck-d)",
    "--radius-sm": "calc(var(--radius) * 0.6)",
    "--radius-md": "calc(var(--radius) * 0.8)",
    "--radius-lg": "var(--radius)",
    "--radius-xl": "calc(var(--radius) * 1.4)",
    "--radius-2xl": "calc(var(--radius) * 1.8)",
    "--radius-3xl": "calc(var(--radius) * 2.2)",
    "--radius-4xl": "calc(var(--radius) * 2.6)",
    "--spacing-safe-top": "var(--safe-top)",
    "--spacing-safe-right": "var(--safe-right)",
    "--spacing-safe-bottom": "var(--safe-bottom)",
    "--spacing-safe-left": "var(--safe-left)",
    "--spacing-control": "var(--control-h)",
    "--spacing-control-sm": "var(--control-h-sm)",
    "--spacing-control-lg": "var(--control-h-lg)",
    "--spacing-row": "var(--row-h)",
    "--shadow-surface": "var(--surface-shadow)",
    "--shadow-glow": "var(--surface-glow)",
    "--blur-surface": "var(--surface-blur)",
    "--ease-out": "var(--ease-out)",
    "--ease-in-out": "var(--ease-in-out)",
    "--ease-spring": "var(--ease-spring)",
    "--animate-fade-in": "fade-in var(--dur-base) var(--ease-out) both",
    "--animate-rise-in": "rise-in var(--dur-base) var(--ease-out) both",
    "--animate-scale-in": "scale-in var(--dur-fast) var(--ease-out) both",
    "--animate-shimmer": "shimmer 1.6s linear infinite",
  };
  for (const name of Object.keys(ROLES.light)) theme[`--color-${name}`] = `var(--${name})`;
  for (const [k, v] of Object.entries(BREAKPOINTS)) theme[`--breakpoint-${k}`] = v;
  for (const [k, v] of Object.entries(CONTENT_WIDTHS)) if (v !== "none") theme[`--container-content-${k}`] = v;

  const keyframes = `@keyframes fade-in { from { opacity: 0 } }
@keyframes rise-in { from { opacity: 0; translate: 0 8px } }
@keyframes scale-in { from { opacity: 0; scale: 0.96 } }
@keyframes shimmer { from { background-position: -200% 0 } to { background-position: 200% 0 } }`;

  const variants = `@custom-variant dark (&:where([data-mode="dark"], [data-mode="dark"] *, .dark, .dark *));
@custom-variant glass (&:where([data-surface="glass"] *));
@custom-variant solid (&:where([data-surface="solid"] *));
@custom-variant flat (&:where([data-surface="flat"] *));
@custom-variant compact (&:where([data-density="compact"] *));
@custom-variant tv (&:where([data-tv] *));
@custom-variant standalone (@media (display-mode: standalone));
@custom-variant ultrawide (@media (min-aspect-ratio: 21/9));
@custom-variant motion-full (&:where([data-motion="full"] *));`;

  const utilities = `@utility surface {
  background-color: color-mix(in oklch, var(--card) calc(var(--surface-alpha) * 100%), transparent);
  -webkit-backdrop-filter: blur(var(--surface-blur));
  backdrop-filter: blur(var(--surface-blur));
  border: 1px solid color-mix(in oklch, var(--foreground) calc(var(--surface-border-alpha) * 100%), transparent);
  box-shadow: var(--surface-shadow);
}
@utility surface-glow { box-shadow: var(--surface-shadow), var(--surface-glow); }
@utility text-gradient-brand {
  background: var(--brand-gradient);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}
@utility text-gradient-accent {
  background: var(--accent-gradient);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}
@utility bg-gradient-accent { background-image: var(--accent-gradient); }
@utility skeleton {
  background: linear-gradient(90deg, var(--muted) 25%, color-mix(in oklch, var(--muted), var(--foreground) 8%) 50%, var(--muted) 75%);
  background-size: 200% 100%;
  animation: var(--animate-shimmer);
  border-radius: var(--radius-md);
}
@utility content-* {
  max-width: var(--content-*);
  margin-inline: auto;
  width: 100%;
}
@utility pb-safe { padding-bottom: max(var(--safe-bottom), --value(--spacing-*)) }
@utility overscan { padding: var(--overscan-y) var(--overscan-x) }
@utility focus-ring {
  outline: var(--focus-ring-w, 2px) solid var(--ring);
  outline-offset: 2px;
}`;

  return [HEADER, dimensionCss(), block("@theme inline", theme), keyframes, variants, utilities].join("\n\n");
}

/** Plain CSS — no Tailwind directives. For tizen, extension, native bootstrap, any vanilla page. */
export function plainCss(): string {
  return [HEADER, dimensionCss()].join("\n\n");
}

export function tokensJson(): string {
  return JSON.stringify(
    {
      accents: ACCENTS,
      roles: ROLES,
      brand: BRAND,
      surface: SURFACE_VARS,
      density: DENSITY_VARS,
      radius: RADIUS_VARS,
      motion: MOTION_VARS,
      breakpoints: BREAKPOINTS,
      contentWidths: CONTENT_WIDTHS,
      zIndex: Z_INDEX,
      fonts: FONTS,
      tv: TV,
      storageKey: PREFS_STORAGE_KEY,
      legacyKeys: LEGACY_KEYS,
      dataAttrs: DATA_ATTRS,
      defaults: DEFAULT_PREFS,
    },
    null,
    2,
  );
}

// ─── Kotlin (Compose) ───────────────────────────────────────────────────────

/** OKLCH → sRGB hex (clamped). Good enough for static Compose colours. */
export function oklchToHex(l: number, c: number, h: number, alpha = 1): string {
  const hr = (h * Math.PI) / 180;
  const a = c * Math.cos(hr);
  const b = c * Math.sin(hr);
  const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = l - 0.0894841775 * a - 1.291485548 * b;
  const L = l_ ** 3, M = m_ ** 3, S = s_ ** 3;
  let r = 4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S;
  let g = -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S;
  let bl = -0.0041960863 * L - 0.7034186147 * M + 1.707614701 * S;
  const gam = (x: number) => {
    const v = Math.min(1, Math.max(0, x));
    return v <= 0.0031308 ? 12.92 * v : 1.055 * Math.pow(v, 1 / 2.4) - 0.055;
  };
  r = gam(r); g = gam(g); bl = gam(bl);
  const hex = (x: number) => Math.round(x * 255).toString(16).padStart(2, "0").toUpperCase();
  return `${hex(alpha)}${hex(r)}${hex(g)}${hex(bl)}`; // AARRGGBB for Compose Color(0x…)
}

export function kotlinTokens(pkg = "ro.mixai.tv.ui.theme"): string {
  const violet = ACCENTS.violet.hue;
  const lines: string[] = [
    `// GENERATED by packages/design-tokens — do not edit. Run: pnpm -C packages/design-tokens build`,
    `package ${pkg}`,
    ``,
    `import androidx.compose.ui.graphics.Color`,
    ``,
    `/** MixAI design tokens (dark mode, violet accent) for the 10-foot UI. */`,
    `object Tokens {`,
  ];
  const camel = (s: string) => s.replace(/-(\w)/g, (_, ch: string) => ch.toUpperCase());
  for (const [name, c] of Object.entries(ROLES.dark)) {
    const hue = c.h === "accent" ? violet : c.h;
    lines.push(`    val ${camel(name)} = Color(0x${oklchToHex(c.l, c.c, hue, c.a ?? 1)})`);
  }
  lines.push(``, `    // Brand signature (fixed)`);
  for (const [k, v] of Object.entries(BRAND)) {
    if (!v.startsWith("#")) continue;
    lines.push(`    val brand${k[0]!.toUpperCase()}${k.slice(1)} = Color(0xFF${v.slice(1).toUpperCase()})`);
  }
  lines.push(``, `    // Accent hues (OKLCH) — for runtime re-tinting if ever needed`);
  for (const [k, v] of Object.entries(ACCENTS)) lines.push(`    const val ACCENT_HUE_${k.toUpperCase()} = ${v.hue}`);
  lines.push(``, `    // 10-foot layout`);
  lines.push(`    const val ROOT_FONT_SP = ${parseInt(TV.rootFontSize, 10)}`);
  lines.push(`    const val FOCUS_RING_DP = ${parseInt(TV.focusRingWidth, 10)}`);
  lines.push(`    const val CARD_SCALE_FOCUSED = ${TV.cardScaleFocused}f`);
  lines.push(`}`, ``);
  return lines.join("\n");
}

// ─── Prehydrate ────────────────────────────────────────────────────────────

/**
 * Inline `<script>` that runs before first paint. Reads `mixai:prefs:v1`
 * (migrating legacy `theme` / `mixai-ui`), resolves `system`, and writes the
 * `data-*` attributes + `.dark` class + `--accent-h` so there is no flash.
 * Kept dependency-free and ES2017 so it also runs in Tizen's Chromium 76.
 */
export function prehydrateScript(): string {
  const accentHues = Object.fromEntries(Object.entries(ACCENTS).map(([k, v]) => [k, v.hue]));
  return `(function(){try{var d=document.documentElement,ls=window.localStorage,K=${JSON.stringify(PREFS_STORAGE_KEY)},H=${JSON.stringify(accentHues)},DEF=${JSON.stringify(DEFAULT_PREFS)};
var raw=ls.getItem(K),p=null;try{p=raw?JSON.parse(raw):null}catch(e){}
if(!p){p={};var t=ls.getItem(${JSON.stringify(LEGACY_KEYS.theme)});if(t==="light"||t==="dark"||t==="system")p.mode=t;
var mu=ls.getItem(${JSON.stringify(LEGACY_KEYS.mixaiUi)});if(mu){try{var m=JSON.parse(mu);var s=m&&m.state?m.state:m;if(s&&s.motion==="minimal")p.motion="reduced";if(s&&s.theme==="flat-pro")p.surface="flat";if(s&&s.theme==="studio-metal")p.surface="solid"}catch(e){}}
var lc=document.cookie.match(/(?:^|; )${LEGACY_KEYS.locale}=(ro|en)/);if(lc)p.locale=lc[1];}
for(var k in DEF)if(p[k]==null)p[k]=DEF[k];
var mode=p.mode==="system"?(window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):p.mode;
d.setAttribute("data-mode",mode);d.classList.remove("light","dark");d.classList.add(mode);d.style.colorScheme=mode;
var ac=String(p.accent),hue=null,attr=ac;if(ac==="artwork"){attr="artwork"}else if(ac.indexOf("custom:")===0){attr="custom";hue=Number(ac.slice(7))}else{hue=H[ac]!=null?H[ac]:H.violet;if(H[ac]==null)attr="violet"}
d.setAttribute("data-accent",attr);if(hue!=null&&isFinite(hue))d.style.setProperty("--accent-h",String(((hue%360)+360)%360));
var coarse=window.matchMedia&&window.matchMedia("(pointer: coarse)").matches;
d.setAttribute("data-surface",p.surface==="glass"&&coarse&&!raw?"solid":p.surface);
d.setAttribute("data-density",p.density);d.setAttribute("data-radius",p.radius);
var rm=window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches;
d.setAttribute("data-motion",rm?"reduced":p.motion);d.setAttribute("lang",p.locale||"ro");
if(!raw)ls.setItem(K,JSON.stringify(p));}catch(e){}})();`;
}
