#!/usr/bin/env node
/**
 * Pre-commit guard for the Next.js web app.
 *
 * If any significant file under app/ is being committed,
 *   - apps/web/package.json
 * must have its `version` field bumped vs the merge base with origin/main.
 *
 * Usage:
 *   node apps/web/scripts/check-version.mjs            # check vs origin/main
 *   node apps/web/scripts/check-version.mjs --staged   # check staged changes (hook mode)
 *   node apps/web/scripts/check-version.mjs --base=<ref>  # custom base ref
 */

import { execFileSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const APP_DIR = resolve(REPO_ROOT, "apps", "web");
const PKG = join(APP_DIR, "package.json");

const args = process.argv.slice(2);
const STAGED = args.includes("--staged");
const baseArg = args.find((a) => a.startsWith("--base="));
const BASE = baseArg ? baseArg.slice("--base=".length) : "origin/main";

const RED = "\u001b[31m";
const GREEN = "\u001b[32m";
const YELLOW = "\u001b[33m";
const DIM = "\u001b[2m";
const BOLD = "\u001b[1m";
const RESET = "\u001b[0m";

function exec(cmd, args) {
    try {
        return execFileSync(cmd, args, {
            cwd: REPO_ROOT,
            encoding: "utf8",
            stdio: ["ignore", "pipe", "pipe"],
        }).trim();
    } catch {
        return null;
    }
}

function changedAppFiles() {
    if (STAGED) {
        const out = exec("git", ["diff", "--cached", "--name-only"]) ?? "";
        return out.split(/\r?\n/).filter((p) => p.startsWith("apps/web/"));
    }
    const baseExists = exec("git", ["rev-parse", "--verify", BASE]);
    if (!baseExists) {
        const out = exec("git", ["status", "--porcelain"]) ?? "";
        return out
            .split(/\r?\n/)
            .map((l) => l.slice(3))
            .filter((p) => p.startsWith("apps/web/"));
    }
    const out = exec("git", ["diff", "--name-only", `${BASE}...HEAD`]) ?? "";
    return out.split(/\r?\n/).filter((p) => p.startsWith("apps/web/"));
}

function readVersionFromHEAD(path) {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, "utf8")).version ?? null;
}

function readVersionFromRef(ref, relPath) {
    const out = exec("git", ["show", `${ref}:${relPath}`]);
    if (!out) return null;
    try {
        return JSON.parse(out).version ?? null;
    } catch {
        return null;
    }
}

function readVersionStaged(path, relPath) {
    const out = exec("git", ["show", `:${relPath}`]);
    if (!out) return readVersionFromHEAD(path);
    try {
        return JSON.parse(out).version ?? null;
    } catch {
        return null;
    }
}

function semverGreater(a, b) {
    if (!a || !b) return false;
    const norm = (v) =>
        v.split(/[.-]/).map((p) => (Number.isFinite(+p) ? Number(p) : p));
    const aa = norm(a);
    const bb = norm(b);
    for (let i = 0; i < Math.max(aa.length, bb.length); i++) {
        const x = aa[i] ?? 0;
        const y = bb[i] ?? 0;
        if (x === y) continue;
        if (typeof x === "number" && typeof y === "number") return x > y;
        return String(x) > String(y);
    }
    return false;
}

function fail(lines) {
    console.error("");
    console.error(`${RED}${BOLD}\u2716 Web app version bump required${RESET}`);
    console.error(`${DIM}${"\u2500".repeat(50)}${RESET}`);
    for (const ln of lines) console.error(ln);
    console.error(`${DIM}${"\u2500".repeat(50)}${RESET}`);
    console.error(`${YELLOW}How to fix:${RESET}`);
    console.error(`  1. Decide the new version (semver: patch / minor / major).`);
    console.error(`  2. Bump ${BOLD}apps/web/package.json${RESET} "version".`);
    console.error(`  3. ${DIM}git add apps/web/package.json${RESET}`);
    console.error(`  4. ${DIM}git commit ...${RESET}`);
    console.error("");
    console.error(
        `${DIM}(To bypass intentionally \u2014 e.g. docs-only or generated-files-only refactor \u2014`,
    );
    console.error(`${DIM} run: git commit --no-verify)${RESET}`);
    console.error("");
    process.exit(1);
}

// ── Main ────────────────────────────────────────────────────────────────
const changed = changedAppFiles().filter((p) => p.length > 0);
if (changed.length === 0) process.exit(0);

// Ignore changes that don't ship code: lockfiles, scripts/, node_modules,
// autogenerated drizzle migrations, ESLint/lint snapshots, local data dirs,
// and test/e2e helpers.
const IGNORED_PREFIXES = [
    "apps/web/node_modules/",
    "apps/web/scripts/",
    "apps/web/drizzle/",
    "apps/web/e2e/",
    "apps/web/data/",
    "apps/web/.next/",
    "apps/web/messages/",
    "apps/web/public/",
];
const IGNORED_FILES = new Set([
    "apps/web/pnpm-lock.yaml",
    "apps/web/eslint-snapshot.json",
    "apps/web/eslint-out.json",
    "apps/web/eslint-out.txt",
    "apps/web/eslint-compact.txt",
    "apps/web/eslint.json",
    "apps/web/lc.json",
    "apps/web/_scan.js",
    "apps/web/parse.js",
    "apps/web/analyze.js",
]);
const significant = changed.filter(
    (p) => !IGNORED_PREFIXES.some((pre) => p.startsWith(pre)) && !IGNORED_FILES.has(p),
);
if (significant.length === 0) process.exit(0);

const pkgRel = "app/package.json";
const currentPkg = STAGED
    ? readVersionStaged(PKG, pkgRel)
    : readVersionFromHEAD(PKG);
const basePkg = readVersionFromRef(BASE, pkgRel);

if (!semverGreater(currentPkg, basePkg)) {
    fail([
        `${BOLD}You changed ${significant.length} file(s) in app/${RESET}`,
        ...significant.slice(0, 8).map((p) => `  ${DIM}\u2026${RESET} ${p}`),
        ...(significant.length > 8
            ? [`  ${DIM}\u2026 and ${significant.length - 8} more${RESET}`]
            : []),
        "",
        `${BOLD}Problem:${RESET}`,
        `  ${RED}\u2022${RESET} app/package.json version is still ${BOLD}${currentPkg ?? "<missing>"}${RESET} (base ${DIM}${basePkg ?? "<unknown>"}${RESET}).`,
    ]);
}

console.log(
    `${GREEN}\u2713${RESET} web app version bumped: ${BOLD}${basePkg ?? "?"}${RESET} \u2192 ${BOLD}${currentPkg}${RESET}`,
);
