-- Saved searches / "smart crates" (Audit round 7).
--
-- A saved library filter — name + the URL-search-param shape that the
-- /library page already understands. Auto-updates by definition: every
-- visit re-runs the filter against the current library, so users get
-- a "what's new in tech-house at 124-128 BPM in 7A/8A" crate that
-- stays fresh without any background job.
--
-- Kept deliberately separate from `smart_playlist_rules` because:
--  * Smart playlists materialise into a real companion playlist row
--    and run a populator job; saved searches are pure read-time filters.
--  * The filter shape mirrors the library page params (15 keys) instead
--    of the discriminated `smartRulesSchema` used for population.
CREATE TABLE IF NOT EXISTS "saved_searches" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" text NOT NULL,
    "name" text NOT NULL,
    "icon" text,
    "filters" jsonb NOT NULL,
    "sort_order" integer NOT NULL DEFAULT 0,
    "created_at" timestamp DEFAULT now(),
    "updated_at" timestamp DEFAULT now()
);

DO $$ BEGIN
    ALTER TABLE "saved_searches"
        ADD CONSTRAINT "saved_searches_user_id_fk"
        FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE INDEX IF NOT EXISTS "saved_searches_user_idx"
    ON "saved_searches" ("user_id", "sort_order");

CREATE UNIQUE INDEX IF NOT EXISTS "saved_searches_user_name_uniq"
    ON "saved_searches" ("user_id", "name");
