-- Video pillar: movies, tv shows, episodes, video files, watch history,
-- ratings, collections, watch profiles, companion devices.

CREATE TABLE IF NOT EXISTS "watch_profiles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "name" text NOT NULL,
    "avatar" text,
    "color" text,
    "is_kid" boolean DEFAULT false NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "prefs" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "watch_profiles_user_idx" ON "watch_profiles" ("user_id","sort_order");

CREATE TABLE IF NOT EXISTS "companion_devices" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "machine_id" text NOT NULL,
    "hostname" text,
    "platform" text,
    "friendly_name" text,
    "color" text,
    "icon" text,
    "public_ip" text,
    "last_seen" timestamp DEFAULT now(),
    "capabilities" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" timestamp DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "companion_devices_user_machine_uniq" ON "companion_devices" ("user_id","machine_id");
CREATE INDEX IF NOT EXISTS "companion_devices_user_idx" ON "companion_devices" ("user_id");

CREATE TABLE IF NOT EXISTS "movies" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "tmdb_id" integer,
    "imdb_id" text,
    "title" text NOT NULL,
    "original_title" text,
    "year" integer,
    "overview" text,
    "tagline" text,
    "runtime_minutes" integer,
    "poster_path" text,
    "backdrop_path" text,
    "trailer_youtube_id" text,
    "genres" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "cast" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "crew" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "rating" real,
    "rating_count" integer,
    "age_rating" text,
    "dominant_color" text,
    "added_at" timestamp DEFAULT now(),
    "updated_at" timestamp DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "movies_user_idx" ON "movies" ("user_id");
CREATE INDEX IF NOT EXISTS "movies_tmdb_idx" ON "movies" ("tmdb_id");
CREATE UNIQUE INDEX IF NOT EXISTS "movies_user_tmdb_uniq" ON "movies" ("user_id","tmdb_id");

CREATE TABLE IF NOT EXISTS "tv_shows" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "tmdb_id" integer,
    "imdb_id" text,
    "title" text NOT NULL,
    "original_title" text,
    "first_air_year" integer,
    "overview" text,
    "poster_path" text,
    "backdrop_path" text,
    "trailer_youtube_id" text,
    "genres" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "cast" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "rating" real,
    "rating_count" integer,
    "age_rating" text,
    "status" text,
    "dominant_color" text,
    "added_at" timestamp DEFAULT now(),
    "updated_at" timestamp DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "tv_shows_user_idx" ON "tv_shows" ("user_id");
CREATE INDEX IF NOT EXISTS "tv_shows_tmdb_idx" ON "tv_shows" ("tmdb_id");
CREATE UNIQUE INDEX IF NOT EXISTS "tv_shows_user_tmdb_uniq" ON "tv_shows" ("user_id","tmdb_id");

CREATE TABLE IF NOT EXISTS "tv_seasons" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "show_id" bigint NOT NULL REFERENCES "tv_shows"("id") ON DELETE CASCADE,
    "season_number" integer NOT NULL,
    "name" text,
    "overview" text,
    "poster_path" text,
    "air_date" timestamp,
    "episode_count" integer
);
CREATE UNIQUE INDEX IF NOT EXISTS "tv_seasons_show_num_uniq" ON "tv_seasons" ("show_id","season_number");

CREATE TABLE IF NOT EXISTS "tv_episodes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "show_id" bigint NOT NULL REFERENCES "tv_shows"("id") ON DELETE CASCADE,
    "season_number" integer NOT NULL,
    "episode_number" integer NOT NULL,
    "title" text,
    "overview" text,
    "runtime_minutes" integer,
    "air_date" timestamp,
    "still_path" text,
    "rating" real,
    "intro_start_sec" real,
    "intro_end_sec" real,
    "credits_start_sec" real
);
CREATE UNIQUE INDEX IF NOT EXISTS "tv_episodes_show_se_ep_uniq" ON "tv_episodes" ("show_id","season_number","episode_number");
CREATE INDEX IF NOT EXISTS "tv_episodes_show_idx" ON "tv_episodes" ("show_id");

CREATE TABLE IF NOT EXISTS "video_files" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "device_id" bigint REFERENCES "companion_devices"("id") ON DELETE CASCADE,
    "kind" text NOT NULL,
    "movie_id" bigint REFERENCES "movies"("id") ON DELETE CASCADE,
    "episode_id" bigint REFERENCES "tv_episodes"("id") ON DELETE CASCADE,
    "path" text NOT NULL,
    "size_bytes" bigint,
    "container" text,
    "video_codec" text,
    "audio_codec" text,
    "width" integer,
    "height" integer,
    "duration_sec" real,
    "bitrate_kbps" integer,
    "hdr" text,
    "audio_tracks" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "subtitle_tracks" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "hash" text,
    "mtime" timestamp,
    "scanned_at" timestamp DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "video_files_user_idx" ON "video_files" ("user_id");
CREATE INDEX IF NOT EXISTS "video_files_movie_idx" ON "video_files" ("movie_id");
CREATE INDEX IF NOT EXISTS "video_files_episode_idx" ON "video_files" ("episode_id");
CREATE INDEX IF NOT EXISTS "video_files_device_idx" ON "video_files" ("device_id");
CREATE UNIQUE INDEX IF NOT EXISTS "video_files_device_path_uniq" ON "video_files" ("device_id","path");

CREATE TABLE IF NOT EXISTS "watch_history" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" bigint NOT NULL REFERENCES "watch_profiles"("id") ON DELETE CASCADE,
    "kind" text NOT NULL,
    "movie_id" bigint REFERENCES "movies"("id") ON DELETE CASCADE,
    "episode_id" bigint REFERENCES "tv_episodes"("id") ON DELETE CASCADE,
    "position_sec" real DEFAULT 0 NOT NULL,
    "duration_sec" real,
    "progress" real DEFAULT 0 NOT NULL,
    "watched_at" timestamp DEFAULT now(),
    "completed" boolean DEFAULT false NOT NULL,
    "play_count" integer DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "watch_history_profile_movie_uniq" ON "watch_history" ("profile_id","movie_id");
CREATE UNIQUE INDEX IF NOT EXISTS "watch_history_profile_episode_uniq" ON "watch_history" ("profile_id","episode_id");
CREATE INDEX IF NOT EXISTS "watch_history_profile_idx" ON "watch_history" ("profile_id","watched_at");

CREATE TABLE IF NOT EXISTS "video_ratings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" bigint NOT NULL REFERENCES "watch_profiles"("id") ON DELETE CASCADE,
    "kind" text NOT NULL,
    "movie_id" bigint REFERENCES "movies"("id") ON DELETE CASCADE,
    "show_id" bigint REFERENCES "tv_shows"("id") ON DELETE CASCADE,
    "rating" integer NOT NULL,
    "rated_at" timestamp DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "video_ratings_profile_movie_uniq" ON "video_ratings" ("profile_id","movie_id");
CREATE UNIQUE INDEX IF NOT EXISTS "video_ratings_profile_show_uniq" ON "video_ratings" ("profile_id","show_id");

CREATE TABLE IF NOT EXISTS "video_collections" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profile_id" bigint NOT NULL REFERENCES "watch_profiles"("id") ON DELETE CASCADE,
    "name" text NOT NULL,
    "kind" text NOT NULL DEFAULT 'custom',
    "description" text,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "video_collections_profile_idx" ON "video_collections" ("profile_id");

CREATE TABLE IF NOT EXISTS "video_collection_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "collection_id" bigint NOT NULL REFERENCES "video_collections"("id") ON DELETE CASCADE,
    "kind" text NOT NULL,
    "movie_id" bigint REFERENCES "movies"("id") ON DELETE CASCADE,
    "show_id" bigint REFERENCES "tv_shows"("id") ON DELETE CASCADE,
    "tmdb_id" integer,
    "tmdb_kind" text,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "added_at" timestamp DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "video_collection_items_collection_idx" ON "video_collection_items" ("collection_id","sort_order");
