// GENERATED by packages/design-tokens — do not edit. Run: pnpm -C packages/design-tokens build
package ro.mixai.tv.ui.theme

import androidx.compose.ui.graphics.Color

/** MixAI design tokens (dark mode, violet accent) for the 10-foot UI. */
object Tokens {
    val background = Color(0xFF07060F)
    val foreground = Color(0xFFF5F1EA)
    val card = Color(0xFF11101A)
    val cardForeground = Color(0xFFF5F1EA)
    val popover = Color(0xFF11101A)
    val popoverForeground = Color(0xFFF5F1EA)
    val primary = Color(0xFF9588FF)
    val primaryForeground = Color(0xFF080715)
    val secondary = Color(0xFF20202B)
    val secondaryForeground = Color(0xFFF5F1EA)
    val muted = Color(0xFF20202B)
    val mutedForeground = Color(0xFF9D9DAB)
    val accent = Color(0xFF2B294B)
    val accentForeground = Color(0xFFD8D7FF)
    val destructive = Color(0xFFFF6367)
    val destructiveForeground = Color(0xFF140505)
    val success = Color(0xFF4BCB71)
    val warning = Color(0xFFF3BA25)
    val info = Color(0xFF42A3FD)
    val border = Color(0x1AFFFFFF)
    val input = Color(0x26FFFFFF)
    val ring = Color(0xFF9588FF)
    val sidebar = Color(0xFF0C0C16)
    val sidebarForeground = Color(0xFFF5F1EA)
    val sidebarPrimary = Color(0xFF9588FF)
    val sidebarPrimaryForeground = Color(0xFF080715)
    val sidebarAccent = Color(0xFF1E1D2D)
    val sidebarAccentForeground = Color(0xFFF5F1EA)
    val sidebarBorder = Color(0x1AFFFFFF)
    val sidebarRing = Color(0xFF9588FF)
    val chart1 = Color(0xFF9588FF)
    val chart2 = Color(0xFFE76EDF)
    val chart3 = Color(0xFF28D6DF)
    val chart4 = Color(0xFF9260DA)
    val chart5 = Color(0xFF50B0FF)

    // Brand signature (fixed)
    val brandViolet = Color(0xFF7C5CFF)
    val brandMagenta = Color(0xFFE84FF0)
    val brandCyan = Color(0xFF22D3EE)
    val brandVioletDark = Color(0xFF8B6DFF)
    val brandMagentaDark = Color(0xFFEF62F3)
    val brandCyanDark = Color(0xFF38DCF2)
    val brandDeckA = Color(0xFF22D3EE)
    val brandDeckB = Color(0xFFFF4FA3)
    val brandDeckC = Color(0xFFA3FF4F)
    val brandDeckD = Color(0xFFFFB14F)

    // Accent hues (OKLCH) — for runtime re-tinting if ever needed
    const val ACCENT_HUE_VIOLET = 285
    const val ACCENT_HUE_MAGENTA = 330
    const val ACCENT_HUE_CYAN = 200
    const val ACCENT_HUE_EMERALD = 160
    const val ACCENT_HUE_AMBER = 75
    const val ACCENT_HUE_ROSE = 15

    // 10-foot layout
    const val ROOT_FONT_SP = 24
    const val FOCUS_RING_DP = 4
    const val CARD_SCALE_FOCUSED = 1.06f
}

