-- 0008_push_subscriptions.sql
-- Additive: stores Web Push subscriptions per (user, endpoint).
-- See app/src/db/schema.ts (`pushSubscriptions`) and the SW push handler
-- in app/public/sw.js. Endpoint is globally unique per Push spec.

CREATE TABLE IF NOT EXISTS "push_subscriptions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "push_subscriptions_id_seq") PRIMARY KEY NOT NULL,
    "user_id" text NOT NULL,
    "endpoint" text NOT NULL,
    "p256dh" text NOT NULL,
    "auth" text NOT NULL,
    "user_agent" text,
    "last_seen_at" timestamp,
    "consecutive_failures" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp DEFAULT now(),
    CONSTRAINT "push_subscriptions_endpoint_unique" UNIQUE("endpoint")
);

DO $$ BEGIN
    ALTER TABLE "push_subscriptions"
        ADD CONSTRAINT "push_subscriptions_user_id_user_id_fk"
        FOREIGN KEY ("user_id") REFERENCES "user"("id")
        ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS "push_subs_user_idx" ON "push_subscriptions" ("user_id");
