-- Smart playlist rules (Batch 40).
--
-- Separate table — keeps the per-field LWW sync on `playlists`
-- untouched and lets the companion adopt the same shape without
-- rewriting its playlists schema. Keyed by (userId, companionPlaylistId)
-- because the UI already passes companion-side ids everywhere.
CREATE TABLE IF NOT EXISTS "smart_playlist_rules" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" text NOT NULL,
    "companion_playlist_id" integer NOT NULL,
    "rules" jsonb NOT NULL,
    "rule_source" text NOT NULL,
    "last_populated_at" timestamp,
    "created_at" timestamp DEFAULT now(),
    "updated_at" timestamp DEFAULT now()
);

-- FK out-of-band so re-running the migration on a partial DB doesn't
-- choke on a duplicate-constraint error.
DO $$ BEGIN
    ALTER TABLE "smart_playlist_rules"
        ADD CONSTRAINT "smart_playlist_rules_user_id_fk"
        FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "smart_rules_user_pl_uniq"
    ON "smart_playlist_rules" ("user_id", "companion_playlist_id");
