-- 0020: recap markers + loudness + bookmarks

ALTER TABLE "tv_episodes"
    ADD COLUMN IF NOT EXISTS "recap_start_sec" real,
    ADD COLUMN IF NOT EXISTS "recap_end_sec" real;

ALTER TABLE "video_files"
    ADD COLUMN IF NOT EXISTS "loudness_integrated" real,
    ADD COLUMN IF NOT EXISTS "loudness_gain_db" real;

CREATE TABLE IF NOT EXISTS "video_bookmarks" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "profile_id" bigint NOT NULL REFERENCES "watch_profiles"("id") ON DELETE CASCADE,
    "kind" text NOT NULL,
    "movie_id" bigint REFERENCES "movies"("id") ON DELETE CASCADE,
    "episode_id" bigint REFERENCES "tv_episodes"("id") ON DELETE CASCADE,
    "file_id" bigint REFERENCES "video_files"("id") ON DELETE SET NULL,
    "time_sec" real NOT NULL,
    "label" text,
    "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "video_bookmarks_profile_idx" ON "video_bookmarks" ("profile_id");
CREATE INDEX IF NOT EXISTS "video_bookmarks_movie_idx" ON "video_bookmarks" ("movie_id");
CREATE INDEX IF NOT EXISTS "video_bookmarks_episode_idx" ON "video_bookmarks" ("episode_id");
