-- Media Home (WP11-02) — expand-only.
-- track_plays: server-side music play log (Continue listening / Recently
-- played rows); replaces the localStorage-only player history.
-- media_sync_state: per-MMO-Server library revision cursor for the
-- server → web /api/media/sync push.
CREATE TABLE IF NOT EXISTS "track_plays" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade,
    "profile_id" bigint REFERENCES "watch_profiles"("id") ON DELETE set null,
    "track_id" integer NOT NULL REFERENCES "tracks"("id") ON DELETE cascade,
    "device_id" text,
    "played_at" timestamptz NOT NULL DEFAULT now(),
    "duration_sec" integer,
    "completed" boolean NOT NULL DEFAULT false,
    "source" text NOT NULL DEFAULT 'web'
);

CREATE INDEX IF NOT EXISTS "track_plays_user_played_idx" ON "track_plays" ("user_id", "played_at" DESC);
CREATE INDEX IF NOT EXISTS "track_plays_track_idx" ON "track_plays" ("track_id");

CREATE TABLE IF NOT EXISTS "media_sync_state" (
    "device_id" text PRIMARY KEY REFERENCES "devices"("id") ON DELETE cascade,
    "revision" integer NOT NULL DEFAULT 0,
    "synced_at" timestamptz NOT NULL DEFAULT now()
);
