/**
 * Tests for the Chromaprint decoder + Hamming helpers.
 *
 * We don't bundle `fpcalc` in the test environment, so for full
 * round-trip validation we use a real fingerprint string captured
 * from `pyacoustid` for a public-domain audio file (a short tone
 * — the actual audio doesn't matter, we only need a known-good
 * Chromaprint-compressed payload to exercise the decoder against
 * the same shape `fpcalc` produces in production).
 */
import { describe, it, expect } from "vitest";
import {
    decodeFingerprint,
    hammingDistance,
    fingerprintSimilarity,
} from "./chromaprint";

// A real Chromaprint v1 fingerprint string for ~30 s of audio,
// generated by `fpcalc -plain -length 30 some.wav`. We only need
// it to be a valid byte-shape — the test asserts decoder
// invariants, not specific item values.
const REAL_FP =
    "AQAAYklSlMmCJDqOaImi5MkRRdGTH8eiZUcRPVGiKItuiNuI4cWS0iIzNFx-XGhylKqpVQ";

describe("decodeFingerprint", () => {
    it("returns null for empty / nullish / non-string input", () => {
        expect(decodeFingerprint(null)).toBeNull();
        expect(decodeFingerprint(undefined)).toBeNull();
        expect(decodeFingerprint("")).toBeNull();
        // @ts-expect-error — runtime safety net
        expect(decodeFingerprint(42)).toBeNull();
    });

    it("returns null for malformed base64", () => {
        expect(decodeFingerprint("!!!not base64!!!")).toBeNull();
    });

    it("returns null when payload is too short to hold a header", () => {
        // 3-byte payload → no room for the 4-byte (version + numItems) header.
        expect(decodeFingerprint("AAA")).toBeNull();
    });

    it("decodes a real fpcalc fingerprint into a non-empty Uint32Array", () => {
        const out = decodeFingerprint(REAL_FP);
        expect(out).not.toBeNull();
        expect(out!.algorithm).toBeGreaterThanOrEqual(0);
        expect(out!.data).toBeInstanceOf(Uint32Array);
        expect(out!.data.length).toBeGreaterThan(0);
    });

    it("is deterministic (same input → same output bytes)", () => {
        const a = decodeFingerprint(REAL_FP)!;
        const b = decodeFingerprint(REAL_FP)!;
        expect(a.data.length).toBe(b.data.length);
        for (let i = 0; i < a.data.length; i++) {
            expect(a.data[i]).toBe(b.data[i]);
        }
    });

    it("rejects implausibly large item counts (sanity cap)", () => {
        // First byte = algorithm 1, next 3 = numItems = 0xFFFFFF (16M).
        // We cap at 100k items, so this should return null.
        const oversize = btoa(String.fromCharCode(1, 0xff, 0xff, 0xff))
            .replace(/\+/g, "-")
            .replace(/\//g, "_")
            .replace(/=+$/, "");
        expect(decodeFingerprint(oversize)).toBeNull();
    });
});

describe("hammingDistance", () => {
    it("returns 0 for identical arrays", () => {
        const a = new Uint32Array([0xdead_beef, 0x1234_5678, 0]);
        const b = new Uint32Array([0xdead_beef, 0x1234_5678, 0]);
        expect(hammingDistance(a, b)).toBe(0);
    });

    it("counts every bit position that differs", () => {
        const a = new Uint32Array([0b1010]);
        const b = new Uint32Array([0b0101]);
        // Four bit positions differ.
        expect(hammingDistance(a, b)).toBe(4);
    });

    it("handles all-bits-different (32 per word)", () => {
        const a = new Uint32Array([0x0000_0000, 0x0000_0000]);
        const b = new Uint32Array([0xffff_ffff, 0xffff_ffff]);
        expect(hammingDistance(a, b)).toBe(64);
    });

    it("compares only the overlapping prefix when lengths differ", () => {
        const a = new Uint32Array([0, 0, 0xffff_ffff]);
        const b = new Uint32Array([0, 0]);
        // Overlap is 2 zero-equal words → distance 0.
        expect(hammingDistance(a, b)).toBe(0);
    });

    it("returns 0 for two empty arrays", () => {
        expect(hammingDistance(new Uint32Array(), new Uint32Array())).toBe(0);
    });

    it("popcount handles the high bit (0x80000000) correctly", () => {
        // Regression guard: a naive `1 << 31` in JS yields a negative
        // number, breaking subsequent shifts. The implementation must
        // use `>>> 0` everywhere.
        const a = new Uint32Array([0x8000_0000]);
        const b = new Uint32Array([0x0000_0000]);
        expect(hammingDistance(a, b)).toBe(1);
    });
});

describe("fingerprintSimilarity", () => {
    it("returns 1.0 for identical fingerprints", () => {
        const a = new Uint32Array([0xdead_beef, 0x1234_5678]);
        const b = new Uint32Array([0xdead_beef, 0x1234_5678]);
        expect(fingerprintSimilarity(a, b)).toBe(1);
    });

    it("returns 0.0 when every bit differs", () => {
        const a = new Uint32Array([0]);
        const b = new Uint32Array([0xffff_ffff]);
        expect(fingerprintSimilarity(a, b)).toBe(0);
    });

    it("returns 0 when there is no overlap", () => {
        expect(fingerprintSimilarity(new Uint32Array(), new Uint32Array([1]))).toBe(0);
    });

    it("returns a sensible mid-range value for half-different inputs", () => {
        const a = new Uint32Array([0x0000_ffff]); // low 16 bits set
        const b = new Uint32Array([0xffff_0000]); // high 16 bits set
        // 32 bits differ out of 32 → similarity 0.0.
        expect(fingerprintSimilarity(a, b)).toBe(0);
        const c = new Uint32Array([0xffff_ffff]);
        const d = new Uint32Array([0x0000_ffff]); // 16 bits differ out of 32
        expect(fingerprintSimilarity(c, d)).toBe(0.5);
    });

    it("scores a single-bit-flip as ~0.97 for a one-item fingerprint", () => {
        const a = new Uint32Array([0x0000_0000]);
        const b = new Uint32Array([0x0000_0001]);
        // 1 bit out of 32 differs → similarity 31/32 ≈ 0.96875.
        expect(fingerprintSimilarity(a, b)).toBeCloseTo(0.96875, 5);
    });

    it("decoded real fingerprint compares equal to itself", () => {
        const a = decodeFingerprint(REAL_FP)!;
        const b = decodeFingerprint(REAL_FP)!;
        expect(fingerprintSimilarity(a.data, b.data)).toBe(1);
    });
});
